### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by yourtypicalbae** [hanahaneull/Discord-Akari#1]
E:\Discord-Akari\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (E:\Discord-Akari\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (E:\Discord-Akari\node_modules\discord.js\src\structures\Guild.js:307:68)
    at new Guild (E:\Discord-Akari\node_modules\discord.js\src\structures\Guild.js:74:12)
    at ClientDataManager.newGuild (E:\Discord-Akari\node_modules\discord.js\src\client\ClientDataManager.js:26:19)
    at ReadyHandler.handle (E:\Discord-Akari\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:20:91)
    at WebSocketPacketManager.handle (E:\Discord-Akari\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (E:\Discord-Akari\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (E:\Discord-Akari\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (E:\Discord-Akari\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)

**Comment by hanahaneull** [comment]
Won't fix. Package issue, and I'm too lazy to find where the error at.
This repo will be Archived later.
